In [2]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

In [3]:
df = sns.load_dataset('titanic')

In [4]:
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [5]:
df.columns

Index(['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'class', 'who', 'adult_male', 'deck', 'embark_town',
       'alive', 'alone'],
      dtype='object')

In [6]:
df.drop(['deck', 'embark_town', 'alone', 'alive', 'class', 'who', 'adult_male'], axis=1, inplace=True)

In [7]:
df['age'].fillna(df['age'].mean(), inplace=True)

In [8]:
df.dropna(subset=['embarked'],inplace=True)

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 889 entries, 0 to 890
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   survived  889 non-null    int64
 1   pclass    889 non-null    int64
 2   sex       889 non-null    object
 3   age       889 non-null    float64
 4   sibsp     889 non-null    int64
 5   parch     889 non-null    int64
 6   fare      889 non-null    float64
 7   embarked  889 non-null    object
dtypes: float64(2), int64(4), object(2)
memory usage: 62.5+ KB

df.

In [10]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [11]:
df['sex'] = le.fit_transform(df['sex'])
df['embarked'] = le.fit_transform(df['embarked'])

In [12]:

df= df.astype(int)

In [13]:
X = df.drop('survived', axis=1)
y = df['survived']

In [14]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [15]:
from sklearn.linear_model import LogisticRegression

In [16]:
model = LogisticRegression()

In [17]:
model.fit(X_train, y_train)

LogisticRegression()

In [18]:
y_pred = model.predict(X_test)

In [19]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [20]:
y_test

281    0
435    1
39     1
418    0
585    1
      ..
433    0
807    0
25     1
85     1
10     1
Name: survived, Length: 178, dtype: int64

In [21]:
accuracy_score(y_test, y_pred)

0.7808988764044944

In [22]:
confusion_matrix(y_test, y_pred)

array([[85, 24],
       [15, 54]])

In [23]:
classification_report(y_test, y_pred)

'              precision    recall  f1-score   support\n\n           0       0.85      0.78      0.81       109\n           1       0.69      0.78      0.73        69\n\n    accuracy                           0.78       178\n   macro avg       0.77      0.78      0.77       178\nweighted avg       0.79      0.78      0.78       178\n'

In [24]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.85      0.78      0.81       109
           1       0.69      0.78      0.73        69

    accuracy                           0.78       178
   macro avg       0.77      0.78      0.77       178
weighted avg       0.79      0.78      0.78       178

In [25]:
df

     survived  pclass  sex  age  sibsp  parch  fare  embarked
0           0       3    1   22      1      0     7         2
1           1       1    0   38      1      0    71         0
2           1       3    0   26      0      0     7         2
3           1       1    0   35      1      0    53         2
4           0       3    1   35      0      0     8         2
..        ...     ...  ...  ...    ...    ...   ...       ...
886         0       2    1   27      0      0    13         2
887         1       1    0   19      0      0    30         2
888         0       3    0   29      1      2    23         2
889         1       1    1   26      0      0    30         0
890         0       3    1   32      0      0     7         1

[889 rows x 8 columns]

In [27]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

In [28]:
x_train_scaled  = scaler.fit_transform(X_train)
x_test_scaled = scaler.transform(X_test)

In [30]:
from sklearn.neighbors import KNeighborsClassifier

In [33]:
knn_model = KNeighborsClassifier(n_neighbors = 5)
knn_model.fit(x_train_scaled, y_train)

KNeighborsClassifier()

In [37]:
y_pred_knn = knn_model.predict(x_test_scaled)

In [38]:
accuracy_score(y_test, y_pred_knn)

0.7865168539325843